error messaging added to template for landing page
miketully426/RoadTripRunner pull request #11
Opened 2021-12-17 03:01 UTC by mgunnhawkins

Error messaging added to landing page.  Errors are black.  Would like to see them be red.  There is already a class added in the template and in css but for some reason they are not connecting.

2021-12-17 20:40 UTC, krystalwhite approved these changes
Error validation works as described.

2021-12-17 21:29 UTC, miketully426 requested changes

2021-12-17 21:29 UTC, miketully426 commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.18'
Fix the indentation, please!

2021-12-22 02:47 UTC, emmykg38 approved these changes
Errors are in place! My only suggestion would be to change the error message for detourRadius to something more user-friendly. Right now it says "must be greater than or equal to 0"  --- could be "Please enter mileage greater than (or equal to) 0" // "Postive miles only :)" etc etc. That's my personal choice/feedback. 
Submitting my approval!

2021-12-27 02:39 UTC, miketully426 approved these changes

2021-12-27 02:40 UTC, merged