Display two locations on map
miketully426/RoadTripRunner pull request #12
Opened 2021-12-17 21:16 UTC by krystalwhite

This code accomplishes a few things:
1. Updated the javascript file to display a starting and ending location with a line between them
2. Updated stylings with the fragments
3. Deleted the style.css file and copied over the #map text to styles.css
4. Organized map information into its own template folder
5. Modified controller to send to mapDisplay.html

This code does NOT take in typed location inputs, but instead provides selections from drop-down menus. The code will need to be refactored to take in typed locations at a future point.

2021-12-17 21:27 UTC, miketully426 requested changes

2021-12-17 21:27 UTC, miketully426 commented on src/main/resources/static/styles.css
> +
Only one space between blocks needed

2021-12-17 21:27 UTC, miketully426 commented on src/main/resources/static/styles.css
> +html,
At least one space between blocks needed

2021-12-17 21:27 UTC, miketully426 commented on src/main/resources/static/script.js
> +    center: { lat: 41.85, lng: -87.65 },
I'd suggest pulling these starting lat-long coordinates and zoom out and setting them as global variables at the start of the file. This way they aren't "magic numbers" in the code and can easily be found to edit in the future.

2021-12-18 02:59 UTC, miketully426 reviewed
Much better! Good job!

2021-12-20 17:49 UTC, emmykg38 approved these changes
Code looks clean (Mike has a meticulous eye I am trying to acquire...)
Nice work, Krystal.

2021-12-21 01:06 UTC, mgunnhawkins approved these changes

2021-12-21 01:07 UTC, miketully426 approved these changes

2021-12-21 01:07 UTC, merged