Display autocomplete directions
miketully426/RoadTripRunner pull request #18
Opened 2022-01-02 20:07 UTC by emmykg38

Here's what we did:

- utilized the autocomplete data to generate a directions renderer
- removed th:elements in the index file to prevent errors from model binding (all th statements are gone!) -- validation code is still happening inside the trip class and will need to be addressed at some point
- added a map to the index.html file to immediately render directions (needs styling/wireframing and design review)

2022-01-03 19:02 UTC, mgunnhawkins commented on src/main/resources/templates/index.html
> +
Remove space

2022-01-03 19:07 UTC, mgunnhawkins requested changes
Hi all!  Great work!
I have a few questions about this branch:
1.  I see that you deleted the detour radius to this page.  Where are we planning to add that in?
2. I also noticed that you removed the name your trip portion.  Where are we planning to add that in?
3. I checked my sql database and noticed that the autocomplete queries are not saving as data into MySQL  are they doing that for you?

Thank you!

2022-01-04 00:35 UTC, valerietonsor approved these changes

2022-01-04 00:38 UTC, valerietonsor requested changes
Hi team! Can you please explain the plan moving forward in regards to deleting the th elements?

2022-01-04 19:12 UTC, emmykg38 commented
This branch is ready to be reviewed again.
More things have changed:

- renamed homecontroller to createtripcontroller to better describe the functionality
- took out methods in renamed createtripcontroller that dealt with model binding of the trip object (which is not possible right now)
- inside authenticationcontroller, we redirected to 'planATrip' template to display map and input directions
- (removed displayMap and replaced it with said planATrip template)
- modified the buttons in the header fragment to reflect changes above
- took out marker and window capability and put it inside a separate function, embedded inside initMap()
- index file now displays only the video and a register button (we did not style or add anything else in here, did not feel it was pertinent to our story)
- changed 'Login/Register' in header fragment to 'Login'
- confirmed that we can drive to anchorage but not to alaska, will need to address status error message for directions renderer in another story
- fingers crossed, if this merges well, this FIXES MAIN

Thank you for your thoughtful review!! (:

2022-01-04 23:41 UTC, valerietonsor approved these changes

2022-01-05 00:13 UTC, mgunnhawkins approved these changes

2022-01-05 00:22 UTC, merged