Login to homepage
miketully426/RoadTripRunner pull request #21
Opened 2022-01-05 22:46 UTC by mgunnhawkins

Things changed:
1.  Moved login to "/"
2. Changed styling on homepage back to flexbox
3. Styled planAtrip with flexbox
4. Styled registration page with flexbox
5. Changed routing from /login to "/" for anything login related

Feedback needed:
1.  I left the login template in just in case there is something wrong.  If everything looks good on the homepage I will delete it.
2.  Look at styling on /register.  Do you like the placeholders better without the labels or with?  Let me know and I will change to group's preference.

2022-01-06 02:11 UTC, valerietonsor commented on src/main/java/com/roadtriprunner/RoadTripRunner/controllers/AuthenticationController.java
> +        return "index";
because this was changed to the index page.... the Login button in the top right corner needs to link to homepage instead of /login

2022-01-06 02:11 UTC, valerietonsor commented on src/main/resources/templates/fragments.html
> +        <a id="login" th:href="@{/}">Login</a>
Huh... this should be working but is giving me a 404 error and still trying to direct to /login

2022-01-06 03:14 UTC, valerietonsor approved these changes

2022-01-06 03:23 UTC, krystalwhite commented
The styling looks great. 
The localhost:/logout page gets a whitepage error

2022-01-07 16:48 UTC, emmykg38 requested changes
Hey, this looks great on my end.
There's an entire template (login.html) that is commented out. Can this be deleted?

2022-01-07 17:54 UTC, mgunnhawkins commented
> 
Perfect!  I will delete now.

2022-01-07 21:44 UTC, emmykg38 approved these changes

2022-01-07 23:03 UTC, merged