View routes
miketully426/RoadTripRunner pull request #6
Opened 2021-12-14 23:16 UTC by emmykg38

basic view of a user's routes completed, can also click to view a very basic itinerary

2021-12-15 03:53 UTC, valerietonsor approved these changes
Looks good! I know we are still working on enum, but for the sake of this story, the trip list is working! Also, styling is not included... but it is in main so it should add it once merged. Awesome job.

2021-12-16 00:35 UTC, miketully426 requested changes

2021-12-16 00:35 UTC, miketully426 commented on src/main/java/com/roadtriprunner/RoadTripRunner/controllers/AuthenticationController.java
> +import com.mysql.cj.x.protobuf.MysqlxDatatypes;
What's this import for?

2021-12-16 00:35 UTC, miketully426 commented on src/main/java/com/roadtriprunner/RoadTripRunner/controllers/HomeController.java
> +        System.out.println("Starting location: " + newTrip.getStartingLocation());
If we're saving the trip into the database, do we need these print lines?

2021-12-16 00:35 UTC, miketully426 commented on src/main/java/com/roadtriprunner/RoadTripRunner/models/Location.java
> +//package com.roadtriprunner.RoadTripRunner.models;
Why is this class commented out?

2021-12-16 00:35 UTC, miketully426 commented on src/main/java/com/roadtriprunner/RoadTripRunner/models/Trip.java
> +    public String getTripName() { return tripName; }
Could we use Lombok instead of these getters and setters?

2021-12-16 00:35 UTC, miketully426 commented on src/main/resources/static/styles.css
> +
Can we clean up some of this white space between the attribute and the closing bracket?

2021-12-16 17:16 UTC, closed without merging