View trips
miketully426/RoadTripRunner pull request #9
Opened 2021-12-16 17:19 UTC by emmykg38

viewTrips allows users to view all of their trips and select a trip to view singular itinerary.
added lombok to the build.gradle file and updated the Trip class to reflect that change.

2021-12-16 21:48 UTC, mgunnhawkins approved these changes
Hi there!  Your code looks good.  Only piece of feedback is that I think it would be more clear if at trips/trip (where you add in the starting and ending locations) that you also had the trip name there.  You completed all of the requirements of the story but this is something you might want to add in.  Well done!

2021-12-17 20:23 UTC, krystalwhite commented on src/main/resources/templates/trips/index.html
> +    <meta charset="UTF-8"/>
Suggested: use head and header fragments so that the styling stays the same

2021-12-17 20:26 UTC, krystalwhite requested changes

2021-12-17 20:26 UTC, krystalwhite commented on src/main/resources/templates/trips/index.html
> +</body>
Suggested: add in footer from fragments

2021-12-17 20:26 UTC, krystalwhite commented on src/main/resources/templates/trips/index.html
> +</head>
Suggested: use head and header fragments so that the styling stays the same

2021-12-17 20:26 UTC, krystalwhite commented on src/main/resources/templates/trips/trip.html
> +    <title></title>
Suggested: use head and header fragments so that the styling stays the same

2021-12-17 20:26 UTC, krystalwhite commented on src/main/resources/templates/trips/trip.html
> +</html>
Suggested: use footer fragments so that the styling stays the same

2021-12-20 18:35 UTC, krystalwhite approved these changes

2021-12-20 18:36 UTC, merged